a=10
b=3.14
c=2+39j
d="Hello"
e=['apple','banana','cherry']
f=(1,3,4,5)
g=range(1,10,2)
h={'Neme':'alice','age':25}
i={1,4,5,5,}
j=frozenset([1,3,4,5,5,6,6,7])
k=True
l=None

check=type(a)
print(check)
check=type(b)
print(check)
check=type(c)
print(check)
check=type(d)
print(check)
check=type(e)
print(check)
check=type(f)
print(check)
check=type(g)
print(check)
check=type(h)
print(check)
check=type(i)
print(check)
check=type(k)
print(check)
check=type(l)
print(check)